security:
    encoders:
        App\Model\UserModel:
            algorithm: bcrypt
            cost: 15

    providers:
        mongodb_provider:
            id: App\Security\UserProvider

    firewalls:
        register:
            pattern:  ^/register
            stateless: true
            anonymous: true
        login:
            pattern: ^/auth
            stateless: true
            anonymous: true
            json_login:
                check_path: /auth
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
        api:
            pattern: ^/api
            stateless: true
            anonymous: false
            provider: mongodb_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.security.guard.jwt_token_authenticator

    # Note: Only the *first* access control that matches will be used
    access_control:
         - { path: ^/auth, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
